version: '3'
services:
  primenumbers:
    build:
      context: .
      args:
        - DIST_FILE=$DIST_FILE
        - DIST_FILE2=$DIST_FILE2
        - DIST_VERSION=$DIST_VERSION
    container_name: primeNumbersApp
    ports:
    - "3333:3333"
  primenumbersvm:
    image: server_primenumbers:latest
    container_name: primeNumbersAppVM
    ports:
      - "3332:3333"
      - "9010:9010"
    environment:
      - >-
          PRIME_NUMBERS_APPLICATION_OPTS=-Dcom.sun.management.jmxremote.port=9010
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false
            -Dcom.sun.management.jmxremote.rmi.port=9010
            -Djava.rmi.server.hostname=localhost

